# Generated by Django 2.0.7 on 2019-07-14 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_file', '0002_auto_20190714_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='documents',
            name='user',
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=None, max_length=40),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='documents',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='upload_file.UserDocuments'),
        ),
        migrations.DeleteModel(
            name='Documents',
        ),
    ]
