# Generated by Django 2.0.7 on 2019-07-16 15:55

from django.db import migrations, models
import upload_file.models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0003_auto_20190714_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=upload_file.models.user_directory_path),
        ),
    ]
