# Generated by Django 2.0.7 on 2019-07-16 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0005_auto_20190716_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documents',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='upload_file.UserDocuments'),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
