# Generated by Django 2.0.7 on 2019-07-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0006_auto_20190716_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
