# Generated by Django 2.0.7 on 2019-07-16 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0007_auto_20190716_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
