# Generated by Django 2.0.7 on 2019-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0008_document_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.AddField(
            model_name='document',
            name='user_text',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
