# Generated by Django 2.0.7 on 2019-07-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0010_document_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
