# Generated by Django 2.0.7 on 2019-07-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0012_auto_20190717_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='anonymized_words',
            field=models.TextField(default=''),
        ),
    ]
