# Generated by Django 2.0.7 on 2019-07-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0013_document_anonymized_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.TextField(default=''),
        ),
    ]
