# Generated by Django 2.0.7 on 2019-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0015_document_anonymized_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(default='anonymous', max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
