# Generated by Django 2.0.7 on 2019-07-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0017_user_user_dictionary'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='change_in_user_dictionary_since_last_update',
            field=models.BooleanField(default=False),
        ),
    ]
