# Generated by Django 2.0.7 on 2019-07-31 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0018_document_change_in_user_dictionary_since_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='change_in_user_dictionary_since_last_update',
        ),
        migrations.AddField(
            model_name='user',
            name='change_in_user_dictionary_since_last_update',
            field=models.BooleanField(default=False),
        ),
    ]
