# Generated by Django 2.0.7 on 2019-09-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0020_auto_20190731_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='delete_words',
            field=models.TextField(default=''),
        ),
    ]
